# Default application configuration that all configurations inherit from.
linters:
  BangFormat:
    enabled: true
    space_before_bang: false

  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: true
    exclude:
      - 'src/styles/structure/mixins.scss'

  ElsePlacement:
    enabled: true

  EmptyLineBetweenBlocks:
    enabled: false

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: false

  HexLength:
    enabled: true
    style: short

  HexNotation:
    enabled: true
    style: uppercase

  HexValidation:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  ImportPath:
    enabled: true
    filename_extension: true

  Indentation:
    enabled: true
    character: tab
    width: 1

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true
    exclude:
      - 'src/styles/structure/selectBoxIt.scss'

  NameFormat:
    enabled: false

  NestingDepth:
    enabled: true

  PlaceholderInExtend:
    enabled: true

  PropertySortOrder:
    enabled: false

  PropertySpelling:
    enabled: true
    extra_properties: []

  QualifyingElement:
    enabled: true

  SelectorDepth:
    enabled: true
    max_depth: 3
    exclude:
      - 'src/styles/structure/selectBoxIt.scss'

  SelectorFormat:
    enabled: false # TODO change once we use BEM
    convention: BEM

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: true

  VendorPrefixes:
    enabled: true

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false